import { NextResponse } from "next/server";

// GET /api/sectors - List sectors and their performance
export async function GET() {
  const sectors = [
    {
      id: "technology",
      name: "Technology",
      performance: {
        day: 1.45,
        week: 3.21,
        month: 5.67,
        ytd: 12.34,
        year: 28.91,
      },
      marketCap: "14.2T",
      topHoldings: ["AAPL", "MSFT", "GOOGL", "NVDA", "META"],
      volume: "3.2B",
      pe: 28.5,
    },
    {
      id: "healthcare",
      name: "Healthcare",
      performance: {
        day: -0.32,
        week: 0.87,
        month: 2.13,
        ytd: 4.56,
        year: 8.23,
      },
      marketCap: "7.8T",
      topHoldings: ["UNH", "JNJ", "LLY", "PFE", "ABBV"],
      volume: "892M",
      pe: 22.3,
    },
    {
      id: "financials",
      name: "Financials",
      performance: {
        day: 0.78,
        week: 1.56,
        month: 3.45,
        ytd: 7.89,
        year: 15.67,
      },
      marketCap: "9.1T",
      topHoldings: ["JPM", "BAC", "WFC", "GS", "MS"],
      volume: "1.1B",
      pe: 14.2,
    },
    {
      id: "consumer-discretionary",
      name: "Consumer Discretionary",
      performance: {
        day: 0.95,
        week: 2.34,
        month: 4.12,
        ytd: 9.45,
        year: 21.34,
      },
      marketCap: "8.5T",
      topHoldings: ["AMZN", "TSLA", "HD", "MCD", "NKE"],
      volume: "1.8B",
      pe: 25.7,
    },
    {
      id: "industrials",
      name: "Industrials",
      performance: {
        day: 0.42,
        week: 1.23,
        month: 2.89,
        ytd: 6.78,
        year: 12.45,
      },
      marketCap: "5.6T",
      topHoldings: ["CAT", "HON", "UNP", "UPS", "BA"],
      volume: "567M",
      pe: 19.8,
    },
    {
      id: "energy",
      name: "Energy",
      performance: {
        day: -1.23,
        week: -2.45,
        month: 1.67,
        ytd: 3.21,
        year: -5.43,
      },
      marketCap: "3.2T",
      topHoldings: ["XOM", "CVX", "COP", "SLB", "EOG"],
      volume: "456M",
      pe: 11.5,
    },
    {
      id: "materials",
      name: "Materials",
      performance: {
        day: 0.21,
        week: 0.89,
        month: 1.45,
        ytd: 4.32,
        year: 9.87,
      },
      marketCap: "2.1T",
      topHoldings: ["LIN", "APD", "SHW", "FCX", "NEM"],
      volume: "234M",
      pe: 16.4,
    },
    {
      id: "utilities",
      name: "Utilities",
      performance: {
        day: -0.15,
        week: 0.34,
        month: 0.78,
        ytd: 2.13,
        year: 5.67,
      },
      marketCap: "1.5T",
      topHoldings: ["NEE", "DUK", "SO", "D", "AEP"],
      volume: "123M",
      pe: 18.9,
    },
    {
      id: "real-estate",
      name: "Real Estate",
      performance: {
        day: 0.56,
        week: 1.12,
        month: 2.34,
        ytd: 5.67,
        year: 7.89,
      },
      marketCap: "1.3T",
      topHoldings: ["PLD", "AMT", "EQIX", "CCI", "PSA"],
      volume: "198M",
      pe: 35.2,
    },
    {
      id: "communication-services",
      name: "Communication Services",
      performance: {
        day: 1.12,
        week: 2.78,
        month: 4.56,
        ytd: 10.23,
        year: 24.56,
      },
      marketCap: "5.9T",
      topHoldings: ["META", "GOOGL", "NFLX", "DIS", "CMCSA"],
      volume: "876M",
      pe: 20.1,
    },
    {
      id: "consumer-staples",
      name: "Consumer Staples",
      performance: {
        day: 0.08,
        week: 0.45,
        month: 1.23,
        ytd: 3.45,
        year: 6.78,
      },
      marketCap: "4.2T",
      topHoldings: ["PG", "KO", "PEP", "COST", "WMT"],
      volume: "345M",
      pe: 21.6,
    },
  ];

  return NextResponse.json({
    success: true,
    data: sectors,
    meta: {
      total: sectors.length,
      timestamp: new Date().toISOString(),
      asOf: new Date().toISOString().split("T")[0],
    },
  });
}
